name: React Frontend Github Pages Deploy

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Token Replacement
        uses: receiptably/variable-substitution@v1
        with:
          files: '**/react_todo_frontend/src/interceptors/appsettings.json'
        env:
            "apiUrl": ${{ secrets.API_URL }}

      - name: npm ci, build
        run: |
          npm ci --legacy-peer-deps
          npm run build
      
      - name: copy in files
        shell: bash
        run: |
          cp ./react_todo_frontend/CNAME ./react_todo_frontend/dist/CNAME
          cp ./react_todo_frontend/dist/index.html ./react_todo_frontend/dist/404.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./react_todo_frontend/dist